name: CI

on:
  push:
    branches: ["**"]
    paths:
      - "**/*.js"
      - "**/*.ts"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/**"
  pull_request:
  workflow_dispatch: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci || npm i --legacy-peer-deps --no-audit --no-fund
      - run: npm run lint --if-present || true

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci || npm i --legacy-peer-deps --no-audit --no-fund
      - run: npm test --if-present -- --ci --reporters=default

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo "React Native build simulated"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "🚀 Simulated deploy of React Native app successful!"
